# Generated by Django 4.1.1 on 2022-09-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('School', 'School'), ('Other', 'Other')], max_length=10),
        ),
    ]
