# Generated by Django 4.1.1 on 2022-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('School', 'School'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work'), ('School', 'School'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='website',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Other', 'Other')], max_length=10),
        ),
    ]
