# Generated by Django 4.1.1 on 2022-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_type_alter_phone_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
